# GitHub Actions workflow for running tests and reporting coverage for the CentrePoint project.

# This workflow is triggered on every push or pull request. It:
# - Sets up a clean Python 3.13 environment
# - Installs project dependencies using `uv`
# - Runs tests using `pytest` with coverage tracking
# - Uploads coverage results to Codecov for visualization and badge integration

name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv + dependencies
        run: |
          pip install uv
          uv pip install --system --editable .

      - name: Run tests with coverage
        run: pytest --import-mode=importlib --cov=src/centrepoint --cov-report=term-missing --cov-report=xml --disable-warnings

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Only needed for private repos
          files: coverage.xml

